site_name: Tema4
theme: windmill

# Nom del lloc
site_name: MKDOCS Web

# Carpeta amb el documents fot
docs_dir: 'md'

# Carpeta on es generar√† el lloc web (mkdocs build)
site_dir: 'docs'
markdown_extensions:
  - admonition
nav:
    - Home: index.md
    - Manuales:
      - Dart: manuales/dart.md
      - Python: manuales/python.md
    - About: about.md


